
name: CI/CD
on:
  pull_request:
#    paths:
#      - 'config/credits.3ncr'
    types:
      - closed
    branches: [main, stage]
  push:
    branches: [main, stage]
  workflow_dispatch:  # Allows manual triggering

env:
  SERVER_USER:  ${{ secrets.SERVER_USER }}
  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
  SERVER_IP:    ${{ github.ref_name == 'main' && secrets.PROD_SERVER_IP || secrets.STAGE_SERVER_IP }}
  SERVER_TEST:  ${{ github.ref_name == 'main' && 'prod env --' || 'stage env --' }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set up PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.0'

      - name: Display ENV (test)
        run: "echo $SERVER_TEST !! test"

#      - name: Install PHP Dependencies
#        run: composer install --prefer-dist --no-progress --no-interaction --no-scripts
#
#      - name: Install NPM Dependencies
#        run: npm install
#
#      - name: Build Frontend Assets
#        run: npm run gulp:build:prod
#
#      - name: Run PHP Tests
#        run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Display ENV (deploy)
        run: "echo $SERVER_TEST !! build"
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Deploy
#        env:
#          DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          ssh -i $DEPLOY_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
#            cd $PRODUCTION_DEPLOY_PATH &&
#            git pull origin production &&
#            composer install --no-dev --no-interaction &&
#            npm ci &&
#            npm run build &&
#            php artisan migrate"
#
#      - name: Tag Production Release
#        if: success()
#        run: |
#          PROD_TAG="prod-$(date +'%Y%m%d%H%M%S')"
#          git tag $PROD_TAG
#          git push origin $PROD_TAG