
name: CI/CD
on:
  pull_request:
    types:
      - closed
    branches: [main, stage]
  push:
    branches: [main, stage]
  workflow_dispatch:  # Allows manual triggering

env:
  SERVER_USER:  ${{ secrets.SERVER_USER }}
  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
  SERVER_IP:    ${{ github.ref_name == 'main' && secrets.PROD_SERVER_IP || secrets.STAGE_SERVER_IP }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

#      - name: Set up PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.0'

      - name: Display ENV (test)
        run: "echo !!-test"

#      - name: Install PHP Dependencies
#        run: composer install --prefer-dist --no-progress --no-interaction --no-scripts

#      - name: Install NPM Dependencies
#        run: npm install
#
#      - name: Build Frontend Assets
#        run: npm run gulp:build:prod

#      - name: Run PHP Tests
#        run: path/to/phpunit

  deploy:
    runs-on: ubuntu-latest
    #needs: build-and-test
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Display ENV (deploy)
        run: "echo !!-build"
#
#      - name: Deploy
#        env:
#          DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          ssh -i $DEPLOY_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
#            cd $PRODUCTION_DEPLOY_PATH &&
#            git pull origin master &&
#            composer install --no-dev --no-interaction &&
#            npm ci &&
#            npm run gulp:build:prod &&
#            php ./scripts/commands config:decrypt"
#
#      - name: Tag Production Release
#        if: success()
#        run: |
#          PROD_TAG="prod-$(date +'%Y%m%d%H%M%S')"
#          git tag $PROD_TAG
#          git push origin $PROD_TAG

#  notification:
#    name: Notify
#    runs-on: ubuntu-latest
#    needs: [deploy]
#    if: always()
#    steps:
#      - uses: martialonline/workflow-status@v3
#        id: check
#      - uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ steps.check.outputs.status }}
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}