
name: Slack
on: 
  pull_request:
    paths:
        - 'config/credits.3ncr'
    types:
      - closed
    branches: [main]

jobs: 
  slack:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps: 
    - name: Notify slack if PR was merged
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C05NDKG5FC0\",\"text\":\"Hey <!here>\nPDFE project (*${{github.ref_name}}*) - `credits.3ncr` file was changed by `${{github.head_ref}}`.\nPlease, update it on your side!\"}'
