
name: Slack
on: 
  pull_request:
    paths:
          - 'config/credits.3ncr'
    types:
      - closed
    branches: [main]

jobs: 
  slack:
    runs-on: ubuntu-latest

    steps: 
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C06JWMNTCA1\",\"text\":\"Test message from Git\"}'
