
name: Slack
on: 
  pull_request:
    paths:
          - 'config/credits.3ncr'
    types:
      - closed
    branches: [main]

jobs: 
  slack:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps: 
    - name: Notify slack if PR was merged
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C06JWMNTCA1\",\"text\":\"PDFE (*${{github.ref_name}}* branch) - Credits file was changed in ${{github.head_ref}}. Do not forget to update it on your side!!!\"}'
